str1=input("str1: ")
str2=input("str2: ")
def scramble(str1,str2):
    if len(str1)>=len(str2):
        A_str2=str2.count("a")
        B_str2=str2.count("b")
        C_str2=str2.count("c")
        D_str2=str2.count("d")
        E_str2=str2.count("e")
        F_str2=str2.count("f")
        G_str2=str2.count("g")
        H_str2=str2.count("h")
        I_str2=str2.count("i")
        J_str2=str2.count("j")
        K_str2=str2.count("k")
        L_str2=str2.count("l")
        M_str2=str2.count("m")
        N_str2=str2.count("n")
        O_str2=str2.count("o")
        P_str2=str2.count("p")
        Q_str2=str2.count("q")
        R_str2=str2.count("r")
        S_str2=str2.count("s")
        T_str2=str2.count("t")
        U_str2=str2.count("u")
        V_str2=str2.count("v")
        W_str2=str2.count("w")
        X_str2=str2.count("x")
        Y_str2=str2.count("y")
        Z_str2=str2.count("z")

        A_str1=str1.count("a")
        B_str1=str1.count("b")
        C_str1=str1.count("c")
        D_str1=str1.count("d")
        E_str1=str1.count("e")
        F_str1=str1.count("f")
        G_str1=str1.count("g")
        H_str1=str1.count("h")
        I_str1=str1.count("i")
        J_str1=str1.count("j")
        K_str1=str1.count("k")
        L_str1=str1.count("l")
        M_str1=str1.count("m")
        N_str1=str1.count("n")
        O_str1=str1.count("o")
        P_str1=str1.count("p")
        Q_str1=str1.count("q")
        R_str1=str1.count("r")
        S_str1=str1.count("s")
        T_str1=str1.count("t")
        U_str1=str1.count("u")
        V_str1=str1.count("v")
        W_str1=str1.count("w")
        X_str1=str1.count("x")
        Y_str1=str1.count("y")
        Z_str1=str1.count("z")
        if A_str1-A_str2>=0 and B_str1-B_str2>=0 and C_str1-C_str2>=0 and D_str1-D_str2>=0 and E_str1-E_str2>=0 and F_str1-F_str2>=0 and G_str1-G_str2>=0 and H_str1-H_str2>=0 and I_str1-I_str2>=0 and J_str1-J_str2>=0 and K_str1-K_str2>=0 and L_str1-L_str2>=0 and M_str1-M_str2>=0 and N_str1-N_str2>=0 and O_str1-O_str2>=0 and P_str1-P_str2>=0 and Q_str1-Q_str2>=0 and R_str1-R_str2>=0 and S_str1-S_str2>=0 and T_str1-T_str2>=0 and U_str1-U_str2>=0 and V_str1-V_str2>=0 and W_str1-W_str2>=0 and X_str1-X_str2>=0 and Y_str1-Y_str2>=0 and Z_str1-Z_str2>=0:
            print(True)
        else:
            print(False)
    else:
        print(False)
scramble(str1,str2)